### ISSUE TITLE
Have worry response,help me

### ISSUE THREAD

**Issue by lastlove-zibin** [1inch/profanity2#15]
![image](https://user-images.githubusercontent.com/23549557/208280540-a28648d9-888a-46b4-9b18-31a1db1708c9.png)
why I cant get the address, just it

**Comment by magic8ytes** [comment]
I think maybe your system does not load OpenCL library or you didn't configure the GPU environment correctly!

**Comment by lastlove-zibin** [comment]
maybe is GPU env, I just try to my vmware. thanks
