### ISSUE TITLE
Devices not detected on WSL2

### ISSUE THREAD

**Issue by cylzxje** [1inch/profanity2#17]
I'm currently on Windows Subsystem for Linux (`WSL`). When i run the command:
`./profanity2.x64 --leading 0000000 -w 256 -z "7d798acc490f26daa63e5239b91c609c290b42cfca72430c098f1521ecd93b2ad79a56030c01122fe25ba84d0f5cddb977bfb9f70e7a959cf884c5e76d5d6c88"`

Output:
```
Mode: leading
Target: Address
Devices:
```
It just stops midway like that. I've tried installing packages such as CUDA, SSH,... for WSL:
https://docs.nvidia.com/cuda/wsl-user-guide/index.html
https://ubuntu.com/tutorials/enabling-gpu-acceleration-on-ubuntu-on-wsl2-with-the-nvidia-cuda-platform#1-overview
It didn't help much. Any idea how to fix or is there any trick to work around this?

**Comment by LokMon** [comment]
With the same problem😭

**Comment by LokMon** [comment]
https://support.zivid.com/en/v2.4/support/clinfo-does-not-print-anything.html
 
 After I follow this document operation, it can run normally. I think you should give it a try.

**Comment by cylzxje** [comment]
> https://support.zivid.com/en/v2.4/support/clinfo-does-not-print-anything.html
> 
> After I follow this document operation, it can run normally. I think you should give it a try.

Ty! It seems like the problem is that OpenCL hasn't supported WSL :/
# https://github.com/microsoft/WSL/issues/6951

**Comment by fabston** [comment]
@cylzxje I was wondering if you were able to run the script now?

**Comment by cylzxje** [comment]
> @cylzxje I was wondering if you were able to run the script now

Sadly, not yet :/

**Comment by fabston** [comment]
> > @cylzxje I was wondering if you were able to run the script now
> 
> Sadly, not yet :/

I was able to set it up and let it run on an Ubuntu CLI server. I took some notes and if you follow these steps it should work:

1. `sudo apt-get install opencl-headers -y && sudo apt-get install make -y && sudo apt-get install g++ -y && sudo apt install clinfo -y`
2. `sudo ln -s /usr/lib/x86_64-linux-gnu/libOpenCL.so.1 /usr/lib/libOpenCL.so`
3. InsInstall [OpenCL](https://support.zivid.com/en/v2.4/getting-started/software-installation/gpu/install-opencl-drivers-ubuntu.html)
4. Get info about GPU with `sudo lshw -C display`
5. Finally compile all the code with `make all`

Hope that helps. Cheers!

**Comment by cylzxje** [comment]
Tho I haven't been able to test this myself cuz my setup is a mess rn, if anyone else successfully run with these steps, plz lmk. Ty!

**Comment by Aziz87** [comment]
> > > @cylzxje I was wondering if you were able to run the script now
> > 
> > 
> > Sadly, not yet :/
> 
> I was able to set it up and let it run on an Ubuntu CLI server. I took some notes and if you follow these steps it should work:
> 
>     1. `sudo apt-get install opencl-headers -y && sudo apt-get install make -y && sudo apt-get install g++ -y && sudo apt install clinfo -y`
> 
>     2. `sudo ln -s /usr/lib/x86_64-linux-gnu/libOpenCL.so.1 /usr/lib/libOpenCL.so`
> 
>     3. InsInstall [OpenCL](https://support.zivid.com/en/v2.4/getting-started/software-installation/gpu/install-opencl-drivers-ubuntu.html)
> 
>     4. Get info about GPU with `sudo lshw -C display`
> 
>     5. Finally compile all the code with `make all`
> 
> 
> Hope that helps. Cheers!

and restart server!

**Comment by calmacfadden** [comment]
I also had to install the nvidia cuda toolkit 

sudo apt install nvidia-cuda-toolkit
